---
apiVersion: v1 
kind: Pod
metadata:
  name: hema
  labels:
    app: web
spec:
  containers:
    - name: caddy
      image: caddy
      ports:
        - containerPort: 80
          protocol: TCP
    - name: jenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
  name: hema
  labels:
    app: web 
spec:
  type: LoadBalancer
  ports:
    - name: caddy
      port: 100
      targetPort: 80
      protocol: TCP
    - name: jenkins
      port: 101
      targetPort: 8080
      protocol: TCP
