apiVersion: v1
kind: deployment
metadata:
  name: deployment
  labels:
    app: httpd
spec:
  minimumReadySec: 5
  replicas: 3
  selector: 
    matchLabels: 
      app: httpd
  strategy:
    type: Rollingupdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 40%
  template:
    metadata:
      name: hop
      labels: 
        app: ram
    spec: 
      containers:
        - name: httpd
          image: httpd
          port:
            containerPort: 80
            hostPort: 80
            protocol: TCP
        

