---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deploy-stateful
  labels: 
    app: mongodb
spec:
  minReadySeconds: 3
  replicas: 3
  selector: 
    matchLabels: 
      app: mongodb
  serviceName: 
  template:
    metadata:
      name: stateful 
      labels:
        app: mongodb 
    spec:
      terminationGracePeriodSeconds: 10 
      containers: 
        - name: mango-db
          image: mongo:4.4
          args: 
            - "--dbpath"
            - "/data/db"
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "rs0"
          ports:
            - containerPort: 27017 
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME 
              value: admin 
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "devops"
          volumeMounts:
            - mountPath: /data/db
              name: pvc-claim
  volumeClaimTemplates:
    metadata:
      name: mongo-db 
      labels:
        app: mongodb 
    spec:
      storageClassName: gp2
      resources:
          requests:
            storage: 1Gi
---
apiVersion: v1 
kind: Service
metadata:
  name: stateful-svc
  labels:
    app: stateful
spec:
  type: ClusterIP 
  selector:
    app: mongodb
  clusterIP: None
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/db